version: '3.7'

services:
    database:
        image: mysql:5.7
        container_name: database
        restart: unless-stopped
        ulimits: # Fix memory leak issue on some systems when LimitNOFILE=infinity (containerd) | https://github.com/docker-library/mysql/issues/873
            nofile:
                soft: 1048576
                hard: 1048576
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=keycloak
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - rede-web-docker

    keycloak:
        image: quay.io/keycloak/keycloak:23.0
        container_name: app-keycloak
        restart: unless-stopped
        environment:
            - KC_DB_URL_HOST=database
            - KC_DB_URL_PORT=3306
            - KC_DB=mysql
            - KC_DB_SCHEMA=keycloak
            - KC_DB_USERNAME=root
            - KC_DB_PASSWORD=root
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
        ports:
            - 8085:8080
        entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
        depends_on:
            - database
        networks:
            - rede-web-docker

    portainer:
        image: portainer/portainer-ce:latest
        container_name: portainer
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./.docker/portainer/data:/data
        command: -H unix:///var/run/docker.sock
        ports:
            - 8086:9000
        networks:
            - rede-web-docker

networks:
    rede-web-docker:
        name: rede-web-docker
        driver: bridge
