version: '3.7'

services:
    mysql:
        image: mysql:5.7
        container_name: mysql_server
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=keycloak
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - rede_web_docker

    keycloak:
        image: jboss/keycloak:16.1.0
        container_name: app_keycloak
        restart: always
        environment:
            - DB_VENDOR=MYSQL
            - DB_ADDR=mysql
            - DB_PORT=3306
            - DB_DATABASE=keycloak
            - DB_USER=root
            - DB_PASSWORD=root
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        ports:
            - 8085:8080
        depends_on:
            - mysql
        networks:
            - rede_web_docker

    portainer:
        image: portainer/portainer:latest
        container_name: portainer
        restart: always
        security_opt:
            - no-new-privileges:true
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./.docker/portainer/data:/data
        command: -H unix:///var/run/docker.sock
        ports:
            - 8086:9000
        networks:
            - rede_web_docker

networks:
    rede_web_docker:
        name: rede_web_docker
        driver: bridge
